### ISSUE TITLE
RSR staking approval failure

### ISSUE THREAD

**Issue by larrythecucumber321** [lc-labs/register#48]
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/71284258/228039807-bb9616d6-5cf6-482d-b4f5-623abe9105a9.png">

**Comment by lcamargof** [comment]
This seems to be an issue specific with the wallet, I remember this to happen with us when multiple people were using the same wallet, maybe a pending tx somewhere?

**Comment by larrythecucumber321** [comment]
Closing as it seems to be a very user-specific issue
