### ISSUE TITLE
Conversion of BigNumber strings to Number causes problems

### ISSUE THREAD

**Issue by larrythecucumber321** [lc-labs/register#5]
Using `parseFloat` to cast a BigNumber (e.g. user balance) to a floating point number causes issues because javascript floating numbers do not go up to 18 decimal precision. 

As an example:
- if the user's on-chain balance is `383392366220969476394`, we'd like to see this represented on the frontend as `383.392366220969476394`
- If `parseFloat(formatEther(383392366220969476394))` is called, it may return a JS number of `383.3923662209695` (see that it's rounded up)
- On the UI, when the user hits 'max' and tries to use this balance, the transaction will fail because they don't have this rounded balance

This issue is manifested here, for example: https://github.com/lc-labs/register/blob/development/src/hooks/useTokensBalance.ts#L34

See these for reference:
https://github.com/pickle-finance/pickle-ui/issues/493
https://github.com/pickle-finance/pickle-ui/pull/500/files

**Comment by lcamargof** [comment]
Fixed on https://github.com/lc-labs/register/pull/20
