### ISSUE TITLE
Use infinite approvals across the app

### ISSUE THREAD

**Issue by larrythecucumber321** [lc-labs/register#63]
aaaaaaahhhhhhh I'm approviinngggg

https://reserve-protocol.slack.com/archives/C045T5DJKFA/p1680573421126999?thread_ts=1680572537.733509&cid=C045T5DJKFA

<img width="528" alt="image" src="https://user-images.githubusercontent.com/71284258/229854241-a1b9adce-41ce-457b-86e2-8b21b68c355e.png">

**Comment by lcamargof** [comment]
Zaps to the rescue, no unlimited approvals planned
